# Generated by Django 4.2 on 2024-10-04 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(db_column='ID_Cargo', primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cargo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estados', models.AutoField(db_column='ID_Estados', primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, db_column='Nombre_estado', max_length=45, null=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion')),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'estados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prioridad', models.AutoField(db_column='ID_Prioridad', primary_key=True, serialize=False)),
                ('nombre_prioridad', models.CharField(blank=True, db_column='Nombre_prioridad', max_length=45, null=True)),
            ],
            options={
                'db_table': 'prioridad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(db_column='ID_Proyecto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, db_column='Duracion_estimada', null=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion')),
                ('fecha_fin_proyecto', models.DateTimeField(db_column='Fecha_Fin_Proyecto')),
                ('estados_id_estados', models.ForeignKey(db_column='Estados_ID_Estados', on_delete=django.db.models.deletion.DO_NOTHING, to='app.estados')),
                ('prioridad_id_prioridad', models.ForeignKey(db_column='Prioridad_ID_Prioridad', on_delete=django.db.models.deletion.DO_NOTHING, to='app.prioridad')),
            ],
            options={
                'db_table': 'proyecto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id_tareas', models.AutoField(db_column='ID_Tareas', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=450, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, db_column='Duracion_estimada', null=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion')),
                ('fecha_fin', models.DateTimeField(db_column='Fecha_Fin')),
                ('prioridad_id_prioridad', models.ForeignKey(db_column='Prioridad_ID_Prioridad', on_delete=django.db.models.deletion.DO_NOTHING, to='app.prioridad')),
                ('proyecto_id_proyecto', models.ForeignKey(db_column='proyecto_ID_Proyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='app.proyecto')),
            ],
            options={
                'db_table': 'tareas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id_subtarea', models.AutoField(db_column='ID_Subtarea', primary_key=True, serialize=False)),
                ('nombre_subtarea', models.CharField(blank=True, db_column='Nombre_Subtarea', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=450, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, db_column='Duracion_estimada', null=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion')),
                ('fecha_fin', models.DateTimeField(db_column='Fecha_Fin')),
                ('tareas_id_tareas', models.ForeignKey(db_column='Tareas_ID_Tareas', on_delete=django.db.models.deletion.DO_NOTHING, to='app.tareas')),
            ],
            options={
                'db_table': 'subtarea',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(db_column='ID_Area', primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(blank=True, db_column='Nombre_Area', max_length=45, null=True)),
                ('descripcion_area', models.CharField(blank=True, db_column='Descripcion_Area', max_length=45, null=True)),
                ('fecha_creada', models.DateTimeField(db_column='Fecha_Creada', default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='Fecha_Actualizacion')),
                ('estados_id_estados', models.ForeignKey(db_column='estados_ID_Estados', on_delete=django.db.models.deletion.DO_NOTHING, to='app.estados')),
            ],
            options={
                'db_table': 'area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_empleado', models.AutoField(db_column='ID_Empleado', primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=45, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=45, null=True)),
                ('correo_electronico', models.CharField(blank=True, db_column='Correo_Electronico', max_length=45, null=True, unique=True)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=500, null=True)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=45, null=True, unique=True)),
                ('login', models.CharField(db_column='Login', max_length=45, unique=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion', default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='Fecha_Actualizacion')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('area_id_area', models.ForeignKey(db_column='area_ID_Area', on_delete=django.db.models.deletion.DO_NOTHING, to='app.area')),
                ('cargo', models.ForeignKey(db_column='Cargo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.cargo')),
                ('estados_id_estados', models.ForeignKey(db_column='estados_ID_Estados', on_delete=django.db.models.deletion.DO_NOTHING, to='app.estados')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'empleados',
                'managed': True,
                'unique_together': {('id_empleado', 'area_id_area')},
            },
        ),
        migrations.CreateModel(
            name='EmpleadosProyecto',
            fields=[
                ('id_emple_vs_proye', models.CharField(db_column='ID_emple_vs_proye', max_length=45, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(db_column='Fecha_asignacion')),
                ('fecha_actualizacion', models.DateTimeField()),
                ('empleados_id_empleado', models.ForeignKey(db_column='Empleados_ID_Empleado', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('proyecto_id_proyecto', models.ForeignKey(db_column='Proyecto_ID_Proyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='app.proyecto')),
            ],
            options={
                'db_table': 'empleados_proyecto',
                'managed': True,
                'unique_together': {('id_emple_vs_proye', 'empleados_id_empleado', 'proyecto_id_proyecto')},
            },
        ),
    ]
