# Generated by Django 4.2 on 2024-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(db_column='ID_Area', primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(blank=True, db_column='Nombre_Area', max_length=45, null=True)),
                ('descripcion_area', models.CharField(blank=True, db_column='Descripcion_Area', max_length=45, null=True)),
                ('fecha_creada', models.DateTimeField(db_column='Fecha_Creada')),
                ('fecha_actualizacion', models.DateTimeField(db_column='Fecha_Actualizacion')),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(db_column='ID_Cargo', primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(db_column='ID_Empleado', primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=45, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=45, null=True)),
                ('correo_electronico', models.CharField(blank=True, db_column='Correo_Electronico', max_length=45, null=True, unique=True)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=500, null=True)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=45, null=True, unique=True)),
                ('login', models.CharField(blank=True, db_column='Login', max_length=45, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion')),
                ('fecha_actualizacion', models.DateTimeField(db_column='Fecha_Actualizacion')),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleadosProyecto',
            fields=[
                ('id_emple_vs_proye', models.CharField(db_column='ID_emple_vs_proye', max_length=45, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(db_column='Fecha_asignacion')),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'empleados_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estados', models.AutoField(db_column='ID_Estados', primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, db_column='Nombre_estado', max_length=45, null=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion')),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prioridad', models.AutoField(db_column='ID_Prioridad', primary_key=True, serialize=False)),
                ('nombre_prioridad', models.CharField(blank=True, db_column='Nombre_prioridad', max_length=45, null=True)),
            ],
            options={
                'db_table': 'prioridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(db_column='ID_Proyecto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, db_column='Duracion_estimada', null=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion')),
                ('fecha_fin_proyecto', models.DateTimeField(db_column='Fecha_Fin_Proyecto')),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id_subtarea', models.AutoField(db_column='Id_subtarea', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion')),
                ('fecha_fin', models.DateTimeField(db_column='Fecha_Fin')),
            ],
            options={
                'db_table': 'subtarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id_tareas', models.AutoField(db_column='ID_Tareas', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=450, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, db_column='Duracion_estimada', null=True)),
                ('fecha_creacion', models.DateTimeField(db_column='Fecha_Creacion')),
                ('fecha_fin', models.DateTimeField(db_column='Fecha_Fin')),
            ],
            options={
                'db_table': 'tareas',
                'managed': False,
            },
        ),
    ]
