# Generated by Django 4.2 on 2024-10-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subtarea',
            table='subtareas',
        ),
    ]
