# Generated by Django 4.2 on 2024-10-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_subtarea_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empleadosproyecto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='prioridad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subtarea',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tareas',
            options={'managed': True},
        ),
    ]
